/*
 * golden_frames.h - byte-exact SCP conformance fixtures (§14).
 *
 * These are the DEFINITION of "correct on the wire" for SCP_PROTO_VERSION 1.
 * They are computed by hand from §5.2's layout (not generated by the code under
 * test) so they independently pin the wire format. Because the header is packed
 * explicitly big-endian, this byte image is identical on every host endianness
 * - which is exactly the property the conformance suite must guard.
 *
 * Treat these bytes as IMMUTABLE for a given SCP_PROTO_VERSION. If a change
 * forces them to differ, that is a breaking protocol change and the version
 * byte must bump.
 */
#ifndef SOLARI_GOLDEN_FRAMES_H
#define SOLARI_GOLDEN_FRAMES_H

#include <stdint.h>

/* Field values that produce GOLDEN_HEADER below. */
#define GF_PROTO_VERSION   0x01
#define GF_MSG_TYPE        0x10            /* SCP_MSG_CLIENT_REPORT          */
#define GF_FLAGS           0x08            /* SCP_FLAG_URGENT                */
#define GF_RESERVED        0x00
#define GF_TLV_COUNT       0x0003
#define GF_SOURCE_NODE_ID  0x0123456789ABCDEFull
#define GF_SEND_TIME_MS    0x0000000100000002ull
#define GF_SEQ_NO          0x11223344u
#define GF_CORRELATION_ID  0xAABBCCDDu

/* The 32-byte header image these fields must serialize to. */
static const uint8_t GOLDEN_HEADER[32] = {
    0x53, 0x4E,             /* magic 'S','N'                       */
    0x01,                   /* protoVersion = 1                    */
    0x10,                   /* msgType = CLIENT_REPORT             */
    0x08,                   /* flags = URGENT                      */
    0x00,                   /* reserved                            */
    0x00, 0x03,             /* tlvCount = 3                        */
    0x01, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF, /* sourceNodeId */
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x02, /* sendTimeUnixMs */
    0x11, 0x22, 0x33, 0x44, /* seqNo                               */
    0xAA, 0xBB, 0xCC, 0xDD  /* correlationId                       */
};

#endif /* SOLARI_GOLDEN_FRAMES_H */
