-- CDC triggers: append to sor_outbox on I/U/D of DNS+core tables (generated)
DROP TRIGGER IF EXISTS trg_entities_ai;
CREATE TRIGGER trg_entities_ai AFTER INSERT ON `entities` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('entities',NEW.id,'insert');
DROP TRIGGER IF EXISTS trg_entities_au;
CREATE TRIGGER trg_entities_au AFTER UPDATE ON `entities` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('entities',NEW.id,'update');
DROP TRIGGER IF EXISTS trg_entities_ad;
CREATE TRIGGER trg_entities_ad AFTER DELETE ON `entities` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('entities',OLD.id,'delete');
DROP TRIGGER IF EXISTS trg_ip_addresses_ai;
CREATE TRIGGER trg_ip_addresses_ai AFTER INSERT ON `ip_addresses` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('ip_addresses',NEW.id,'insert');
DROP TRIGGER IF EXISTS trg_ip_addresses_au;
CREATE TRIGGER trg_ip_addresses_au AFTER UPDATE ON `ip_addresses` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('ip_addresses',NEW.id,'update');
DROP TRIGGER IF EXISTS trg_ip_addresses_ad;
CREATE TRIGGER trg_ip_addresses_ad AFTER DELETE ON `ip_addresses` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('ip_addresses',OLD.id,'delete');
DROP TRIGGER IF EXISTS trg_interfaces_ai;
CREATE TRIGGER trg_interfaces_ai AFTER INSERT ON `interfaces` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('interfaces',NEW.id,'insert');
DROP TRIGGER IF EXISTS trg_interfaces_au;
CREATE TRIGGER trg_interfaces_au AFTER UPDATE ON `interfaces` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('interfaces',NEW.id,'update');
DROP TRIGGER IF EXISTS trg_interfaces_ad;
CREATE TRIGGER trg_interfaces_ad AFTER DELETE ON `interfaces` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('interfaces',OLD.id,'delete');
DROP TRIGGER IF EXISTS trg_dns_records_ai;
CREATE TRIGGER trg_dns_records_ai AFTER INSERT ON `dns_records` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('dns_records',NEW.id,'insert');
DROP TRIGGER IF EXISTS trg_dns_records_au;
CREATE TRIGGER trg_dns_records_au AFTER UPDATE ON `dns_records` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('dns_records',NEW.id,'update');
DROP TRIGGER IF EXISTS trg_dns_records_ad;
CREATE TRIGGER trg_dns_records_ad AFTER DELETE ON `dns_records` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('dns_records',OLD.id,'delete');
DROP TRIGGER IF EXISTS trg_dns_zones_ai;
CREATE TRIGGER trg_dns_zones_ai AFTER INSERT ON `dns_zones` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('dns_zones',NEW.id,'insert');
DROP TRIGGER IF EXISTS trg_dns_zones_au;
CREATE TRIGGER trg_dns_zones_au AFTER UPDATE ON `dns_zones` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('dns_zones',NEW.id,'update');
DROP TRIGGER IF EXISTS trg_dns_zones_ad;
CREATE TRIGGER trg_dns_zones_ad AFTER DELETE ON `dns_zones` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('dns_zones',OLD.id,'delete');
DROP TRIGGER IF EXISTS trg_networks_ai;
CREATE TRIGGER trg_networks_ai AFTER INSERT ON `networks` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('networks',NEW.id,'insert');
DROP TRIGGER IF EXISTS trg_networks_au;
CREATE TRIGGER trg_networks_au AFTER UPDATE ON `networks` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('networks',NEW.id,'update');
DROP TRIGGER IF EXISTS trg_networks_ad;
CREATE TRIGGER trg_networks_ad AFTER DELETE ON `networks` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('networks',OLD.id,'delete');
DROP TRIGGER IF EXISTS trg_subnets_ai;
CREATE TRIGGER trg_subnets_ai AFTER INSERT ON `subnets` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('subnets',NEW.id,'insert');
DROP TRIGGER IF EXISTS trg_subnets_au;
CREATE TRIGGER trg_subnets_au AFTER UPDATE ON `subnets` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('subnets',NEW.id,'update');
DROP TRIGGER IF EXISTS trg_subnets_ad;
CREATE TRIGGER trg_subnets_ad AFTER DELETE ON `subnets` FOR EACH ROW INSERT INTO sor_outbox (table_name,row_id,action) VALUES ('subnets',OLD.id,'delete');
